### ISSUE TITLE
Known letters from other wordles don't show up on keyboard

### ISSUE THREAD

**Issue by RileyChang** [mmmewk/crosswordle#1]
For example, in the screenshot, I would want the 'L' key on the keyboard to be green.

<img width="1351" alt="Screen Shot 2022-01-22 at 10 05 56 PM" src="https://user-images.githubusercontent.com/4986478/150666913-94bfa363-3f49-4a0c-ae29-750272c302dc.png">

**Comment by mmmewk** [comment]
Implemented!
