### ISSUE TITLE
Unicode Puzzle Character Issues

### ISSUE THREAD

**Issue by muhelen** [mmmewk/crosswordle#11]
Hi, while forking to build on my Tamil language, I stumbled upon some unicode character problem on Crossword.tsx file with _**guessedLetter**_. 

<img width="781" alt="Screenshot 2022-03-02 at பிற்பகல் 9 16 06" src="https://user-images.githubusercontent.com/5513469/156368785-db0b5bad-790d-4158-8652-3661df466a44.png">
If you could see on the screenshot, I've implemented grapheme splitter to the grid letters and it works, but unable to do it on the puzzle box. Could you point me the right way to fix this? Thanks.

**Comment by mmmewk** [comment]
Hmm, I can take a look tonight but not sure if I would know any better than you why its not working. Can you make sure your forked project is up to date on github so I can clone it locally and play around?

**Comment by muhelen** [comment]
> Hmm, I can take a look tonight but not sure if I would know any better than you why its not working. Can you make sure your forked project is up to date on github so I can clone it locally and play around?

Hi, Thanks for the reply. I've updated my fork with some easy Tami. keyboard layout for your testing. 

<img width="615" alt="Screenshot 2022-03-03 at முற்பகல் 1 03 47" src="https://user-images.githubusercontent.com/5513469/156412473-b036c671-4c73-4b44-82c2-12216ceaa61f.png">

First row = dependants , Second row = vowels, Third & forth row = consonants
Vowels are independent characters, while **consonants + dependants** will form compound (combine) consonants.

It's basically last two rows + first row characters will form 1 joined letter.  Let me know if you need further help on this layout understanding.

**Comment by muhelen** [comment]
> I also wonder if we can make the separate language builds part of this one. Maybe a language selector at the top and then each language has its own set of puzzles? That way as new features are added to the original build they get applied to all languages.
> 
> If we go down that route it would be cool to have a dictionary feature when you can click on a word and it tells you what it means, that way language learners can use this game to expand their vocabulary.

This is good suggestions, but it may require further extra development on different language complexity. For Tamil, it's total of 247 letters altogether. I'm keen on this development, but not sure about other languages. Let's explore it and sure it will be a good learning experiences and will benefit more larger communities.

**Comment by mmmewk** [comment]
Ok I think I understand the issue:

1) You need to update the `getGuessedLetter` function to use your unicode splitter on the return statement. This is the function that sets the blue text.
2) you need to update the `guessWord` function where it says `Array.from(guess)` you want to use your unicode splitter. That is the function that saves whatever letters you got correct to the crossword grid.

**Comment by mmmewk** [comment]
2 other issues I see:
1) The font size of the the letters maybe needs to get smaller if they are really long to fit in the squares
2) My function `moveToNextGuessSquare` was implemented pretty lazily assuming that each keystroke would be a single character. It actually works off the fact that the state of `currentGuess` hasn't yet updated. I'll fix that in my code too.

This should work instead for you:
```
  // After keyboard input move to the next square where you can type
  const moveToLetterIndex = useCallback((index: number) => {
    let { row, col } = focusedWordData;
    if (focusedDirection === 'across') col += index;
    if (focusedDirection === 'down') row += index;
    crosswordRef.current?.moveTo(row, col);
  }, [focusedDirection, crosswordRef, focusedWordData]);

  // Key event callbacks
  const onChar = (value: string) => {
    const guessesForWord = guesses[focusedDirection][focusedNumber];

    if (unicodeLength(currentGuess) < currentWord.length && guessesForWord.length < 6) {
      const newGuess = `${currentGuess}${value}`;
      setCurrentGuess(newGuess);
      moveToLetterIndex(unicodeLength(newGuess));
    }
  }

  const onDelete = () => {
    const newGuess = currentGuess.slice(0, -1);
    setCurrentGuess(newGuess);
    moveToLetterIndex(unicodeLength(newGuess));
  }
```

**Comment by mmmewk** [comment]
Hope that helps! Stoked to see your version live!

**Comment by muhelen** [comment]
> 2 other issues I see:
> 
> 1. The font size of the the letters maybe needs to get smaller if they are really long to fit in the squares
> 2. My function `moveToNextGuessSquare` was implemented pretty lazily assuming that each keystroke would be a single character. It actually works off the fact that the state of `currentGuess` hasn't yet updated. I'll fix that in my code too.
> 
> This should work instead for you, instead of moving relative to your current position when you type move to the square that is unicodeLength(newGuess) away from the start:
> 
> ```
>   // After keyboard input move to the next square where you can type
>   const moveToLetterIndex = useCallback((index: number) => {
>     let { row, col } = focusedWordData;
>     if (focusedDirection === 'across') col += index;
>     if (focusedDirection === 'down') row += index;
>     crosswordRef.current?.moveTo(row, col);
>   }, [focusedDirection, crosswordRef, focusedWordData]);
> 
>   // Key event callbacks
>   const onChar = (value: string) => {
>     const guessesForWord = guesses[focusedDirection][focusedNumber];
> 
>     if (unicodeLength(currentGuess) < currentWord.length && guessesForWord.length < 6) {
>       const newGuess = `${currentGuess}${value}`;
>       setCurrentGuess(newGuess);
>       moveToLetterIndex(unicodeLength(newGuess));
>     }
>   }
> 
>   const onDelete = () => {
>     const newGuess = currentGuess.slice(0, -1);
>     setCurrentGuess(newGuess);
>     moveToLetterIndex(unicodeLength(newGuess));
>   }
> ```

Hi @mmmewk Yes, this works for the guesses. 👍🏼

> @muhelen Ok I think I understand the issue:
> 
> 1. You need to update the `getGuessedLetter` function to use your unicode splitter on the return statement. This is the function that sets the blue text.
> 2. you need to update the `guessWord` function where it says `Array.from(guess)` you want to use your unicode splitter. That is the function that saves whatever letters you got correct to the crossword grid.

But, I'm still struggling with this code. Could you provide me some example. The puzzle grid still couldn't ...

**Comment by mmmewk** [comment]
Yeah for `getGuessedLetter`:

```
const getGuessedLetter = (cell: CellData) => {
    if (!cell.used || !guess) return;


    const focusedNumber = focusedCell[focusedDirection];

    if (!focusedNumber || cell[focusedDirection] !== focusedNumber) return;
    const focusedWord = crossword[focusedDirection][focusedNumber];
    const letterIndex = cell.row - focusedWord.row || cell.col - focusedWord.col;
    return unicodeSplit(guess)[letterIndex];
  };
```

and for `guessWord`:
```
guessWord: (guess: string) => {
      const focusedNumber = focusedCell[focusedDirection];

      if (!focusedNumber) return;
      const focusedWord = crossword[focusedDirection][focusedNumber];

      const gridDataClone = cloneDeep(gridData);

      let { row, col, answer } = focusedWord;
      unicodeSplit(guess).forEach((letter, index) => {
        const newRow = row + (focusedDirection === 'down' ? index : 0);
        const newCol = col + (focusedDirection === 'across' ? index : 0);
        const cellClone = gridDataClone[newRow][newCol];
        if (!cellClone.used) return;
        if (letter === answer[index]) cellClone.guess = letter;
      });

      setGridData(gridDataClone);
    },
```

**Comment by mmmewk** [comment]
Let me know if that works as expected!

**Comment by muhelen** [comment]
> Yeah for `getGuessedLetter`:
> 
> ```
> const getGuessedLetter = (cell: CellData) => {
>     if (!cell.used || !guess) return;
> 
> 
>     const focusedNumber = focusedCell[focusedDirection];
> 
>     if (!focusedNumber || cell[focusedDirection] !== focusedNumber) return;
>     const focusedWord = crossword[focusedDirection][focusedNumber];
>     const letterIndex = cell.row - focusedWord.row || cell.col - focusedWord.col;
>     return unicodeSplit(guess)[letterIndex];
>   };
> ```
> 
> and for `guessWord`:
> 
> ```
> guessWord: (guess: string) => {
>       const focusedNumber = focusedCell[focusedDirection];
> 
>       if (!focusedNumber) return;
>       const focusedWord = crossword[focusedDirection][focusedNumber];
> 
>       const gridDataClone = cloneDeep(gridData);
> 
>       let { row, col, answer } = focusedWord;
>       unicodeSplit(guess).forEach((letter, index) => {
>         const newRow = row + (focusedDirection === 'down' ? index : 0);
>         const newCol = col + (focusedDirection === 'across' ? index : 0);
>         const cellClone = gridDataClone[newRow][newCol];
>         if (!cellClone.used) return;
>         if (letter === answer[index]) cellClone.guess = letter;
>       });
> 
>       setGridData(gridDataClone);
>     },
> ```

@mmmewk Yes, its now combining the characters correctly. But the last letters not working properly. It's jumping to next word when doing the combination...

**Comment by mmmewk** [comment]
Ahh yeah are there certain queues you can use to know when the letter is completed? You can just remove the whole moveToNextGuessSquare logic, it was just a convenience thing. Or if you know that a letter is complete only then do you move to the next square

**Comment by muhelen** [comment]
@mmmewk That's great news 😊👌👌 Meanwhile I'll try to use my modified version unicode splitter.. Thanks.

**Comment by muhelen** [comment]
Hi @mmmewk, I've fixed some other unicode related errors. I've noticed you've changed to `moveToIndex`.  I'm still stuck with that.

The guess box still showing here :
<img width="429" alt="Screenshot 2022-03-04 at பிற்பகல் 11 20 05" src="https://user-images.githubusercontent.com/5513469/156790498-6cdcc419-fd14-40ed-98de-2eded65ae1bc.png">

But when I enter the last combine character, it's disappearing, for desktop it's only showing next 5 guesses box :
<img width="397" alt="Screenshot 2022-03-04 at பிற்பகல் 11 20 15" src="https://user-images.githubusercontent.com/5513469/156791372-dc728d06-b653-46bb-90ff-f40cb6008832.png">


If I remove this code altogether, its still same : 
`  const moveToIndex = useCallback((index: number) => {
    let { row, col } = focusedWordData;
    if (focusedDirection === 'across') col += index;
    if (focusedDirection === 'down') row += index;
    crosswordRef.current?.moveTo(row, col);
  }, [focusedDirection, crosswordRef, focusedWordData]);`

Could you let me know how do I fix this?

**Comment by muhelen** [comment]
@mmmewk I've rectified most of the unicode errors. I'm having an issue as below :

When enter the correct word on the guesses, it doesn't return anything. If I enter additional letter, the screen goes blank. If enter wrong word, it return word not found message.

You can check my fork repo. Could you highlight me what's not woking here. Thanks.

**Comment by mmmewk** [comment]
Hey, sorry was out of town this last weekend. I can take a look today or tomorrow after work, for the word not found message you need to update `public/validWords.json` to include words in your language, right now it only includes english words of 3-5 letters

**Comment by mmmewk** [comment]
For the correct word I'm not sure, try seeing if there are any console errors?

**Comment by muhelen** [comment]
@mmmewk Hi, yes I already updated the validwords.json with Tamil words with many combinations. Hope you can find out why the errors occurs. Thanks.

**Comment by mmmewk** [comment]
Created a PR into your branch, just more locations where you need to use unicodeLength rather than `.length`

**Comment by mmmewk** [comment]
Closing this issue as its related to your fork rather than mine, Happy to help in the future though looks like your branch is pretty close to working!

**Comment by muhelen** [comment]
> Created a PR into your branch, just more locations where you need to use unicodeLength rather than `.length`

Hi, I can't view the PR. Could you resend again? Thanks.

**Comment by mmmewk** [comment]
Oops sorry, just reopened it
