### ISSUE TITLE
Bookmark/Home Screen shortcut blank

### ISSUE THREAD

**Issue by muhelen** [mmmewk/crosswordle#16]
@mmmewk Hi, I've noticed your recent build caused blank screen on my existing iOS shortcut. I need to re-save to play again. Kindly check. Thanks.

**Comment by mmmewk** [comment]
Hmm, I can't reproduce this. Hard to say whats going on without steps to reproduce... Probably something with old stale data being persisted into state.

**Comment by mmmewk** [comment]
Should be fixed now, can you confirm?

**Comment by muhelen** [comment]
Hi, I can't reproduce the error again as I've updated a new bookmark earlier. Hope someone else can verify on this. Thanks.

**Comment by mmmewk** [comment]
I added an error page that notifies the user to write a bug report, so I'm going to close this for now until someone brings it back up

**Comment by muhelen** [comment]
Okay great 👍
