### ISSUE TITLE
Polish: Make keyboard unselectable

### ISSUE THREAD

**Issue by nik3daz** [mmmewk/crosswordle#32]
![image](https://user-images.githubusercontent.com/1677402/158736118-540ca187-5cb1-4fa5-8bae-187ba18a163a.png)
![image](https://user-images.githubusercontent.com/1677402/158736127-00bd49f6-e0c6-4583-99a2-27931323aa0c.png)

When I press Enter and a word isn't found, it selects the text in the keyboard.

Adding `user-select: none` to the keyboard (maybe even the whole page?) should fix it. 

Android Phone using Chrome

**Comment by mmmewk** [comment]
Implemented your fix, thanks for pointing it out! Feel free to reopen the issue if you continue seeing it!
