### ISSUE TITLE
Feature Request : Reveal word on Fail

### ISSUE THREAD

**Issue by muhelen** [mmmewk/crosswordle#34]
I'm adding a feedback I've received :
_It can be a little frustrating if after 6 tries we fail to find the word and if the the word is not revealed. You may want to consider revealing the answer after the permitted 6 tries._

**Comment by mmmewk** [comment]
Ahh thats a good call, I'll make the puzzle reveal itself if the user looses

**Comment by muhelen** [comment]
Great 👍🏼

**Comment by mmmewk** [comment]
https://github.com/mmmewk/crosswordle/pull/36

**Comment by muhelen** [comment]
@mmmewk Hey thanks for the add. It's works great 👍🏼

**Comment by muhelen** [comment]
Hi @mmmewk, for some unknown reason, the reveal word not working today. It's working fine yesterday. Could you check it out again . Thanks.
