### ISSUE TITLE
Feature Request: Record the completion time

### ISSUE THREAD

**Issue by RileyChang** [mmmewk/crosswordle#7]
I really want to know how long it took me to do the crosswordle, just like the NYT mini. Bonus points for leaderboards (this could just be a global leaderboard of sorts?).

**Comment by mmmewk** [comment]
Completed!

**Comment by nik3daz** [comment]
If the timer is showing, can you also add the completion time to the share string?

Thaaaanks <3

**Comment by mmmewk** [comment]
Done!
