### ISSUE TITLE
Mobile Grid > Too Small

### ISSUE THREAD

**Issue by muhelen** [mmmewk/crosswordle#8]
<img width="565" alt="Screenshot 2022-02-28 at முற்பகல் 6 56 38" src="https://user-images.githubusercontent.com/5513469/155903520-db0ffce1-9b4a-4825-8f1d-7861e4457f26.png">
The main puzzle grid looks too small on the mobile phones screen. For desktop and tablet not an issue.

**Comment by mmmewk** [comment]
Ahh good callout, I want to make sure the keyboard is big enough to use and its pretty hard to fit all this information on the screen, but I'll see what I can do

**Comment by muhelen** [comment]
Great. Thanks for your marvelous effort on this.

**Comment by muhelen** [comment]
![image](https://user-images.githubusercontent.com/5513469/155997827-0992ea86-2c6c-484f-8242-1e245cbd8bc5.png)
This is how it's look on iOS. The bottom got plenty of space after keyboard. Even if the puzzle board increase the size, the keyboard still could maintain the current siZe. Just my thoughts..

**Comment by muhelen** [comment]
Hi @mmmewk Thanks for the PR add. I’m closing this as the issues resolved.
